version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
platform:
  - x86
  - x64
  - ARM
  - ARM64  
configuration:
  - Debug
  - Release
before_build:
  - nuget restore msvc\corehook.sln
build:
  project: msvc\corehook.sln
  verbosity: detailed
skip_commits:
  files:
    - '**/*.md'
artifacts:
- path: bin.x86\Release\corehook32.dll
  name: corehook-X86
- path: bin.x64\Release\corehook64.dll
  name: CoreHook-X64  
- path: bin.ARM\Release\corehook32.dll
  name: corehook-ARM
- path: bin.ARM64\Release\corehook64.dll
  name: corehook-ARM64      