version: 1.0.{build}
branches:
  only:
  - dev-arm
skip_tags: true
image: Visual Studio 2017
platform:
  - x86
  - x64
configuration:
  - Debug
  - Release
build:
  project: msvc\corehook.sln
  verbosity: detailed